# Generated by Django 4.2.5 on 2023-11-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
